// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTracking.DAL.EF;

namespace ProductTracking.DAL.Migrations
{
    [DbContext(typeof(ProductTrackingContext))]
    partial class ProductTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductTracking.DAL.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryWay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryWay = 0,
                            Name = "Grodno"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryWay = 2,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryWay = 2,
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Grodno",
                            Country = "Belarus",
                            Name = "MilkWorld",
                            Registered = true
                        },
                        new
                        {
                            Id = 2,
                            City = "Malmo",
                            Country = "Sweden",
                            Name = "StockFood",
                            Registered = true
                        },
                        new
                        {
                            Id = 3,
                            City = "Tucson",
                            Country = "USA",
                            Name = "EaterCorp",
                            Registered = true
                        });
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Calority")
                        .HasColumnType("float");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int?>("RealizationPlaceId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RealizationPlaceId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.RealizationPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RealizationPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Almi",
                            WorkTime = 11
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Euroopt",
                            WorkTime = 10
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Walmart",
                            WorkTime = 8
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Auchan",
                            WorkTime = 9
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Green",
                            WorkTime = 10
                        });
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "meister",
                            Password = "25D55AD283AA400AF464C76D713C07AD",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.Product", b =>
                {
                    b.HasOne("ProductTracking.DAL.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ProductTracking.DAL.Entities.RealizationPlace", "RealizationPlace")
                        .WithMany("Products")
                        .HasForeignKey("RealizationPlaceId");
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.RealizationPlace", b =>
                {
                    b.HasOne("ProductTracking.DAL.Entities.City", "City")
                        .WithMany("RealizationPlaces")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("ProductTracking.DAL.Entities.User", b =>
                {
                    b.HasOne("ProductTracking.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
